extends: ['@sripwoud']
overrides:
  - files: ['test/jest.config.ts']
    rules:
      '@typescript-eslint/no-non-null-assertion': off
  - files: ['src/**/*.ts']
    rules:
      '@typescript-eslint/dot-notation': off
